[phases.setup]
aptPkgs = ["libgl1", "libglib2.0-0"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install opencv-python-headless==4.10.0.84",
  ". /opt/venv/bin/activate && pip install rapidocr-onnxruntime",
  ". /opt/venv/bin/activate && pip uninstall -y opencv-python || true",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]
