[phases.setup]
aptPkgs = [
  "libgl1",
  "libglib2.0-0",
  "libsm6",
  "libxrender1",
  "libxext6",
  "libxcb1",
  "libgomp1",
  "libxcb-xkb1",
  "libxcb-icccm4",
  "libxcb-image0",
  "libxcb-render-util0",
  "libxcb-randr0",
  "libxcb-keysyms1",
  "libxcb-shape0",
  "libxkbcommon-x11-0",
  "libxcb-shm0"
]
